
jobs:
  build:
    steps:
    - name: code
      uses: actions/checkout@v3
    
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        # cache: 'npm'
    - run: |
        cd documentation         
        npm i
        npm run build 
    