name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code
      uses: actions/checkout@v3
    
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        # cache: 'npm'
    - run: |
        cd documentation  
        cd syncPowershell       
        npm i
        npm run build 
        ls -lh
                
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: docusaurusBuild
        path: 'documentation/syncPowershell/build/*'
        retention-days: 1

    - name: upload documentation to github pages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        cp -r documentation/syncPowershell/build/* docs/

    - uses: EndBug/add-and-commit@v9
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        message: 'Deploy documentation'
        default_author: github_actions
        cwd: './docs'

      