name: build

on:
  workflow_call:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code
      uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        # cache: 'npm'
    - name: build documentation
      run: |
        cd documentation  
        cd syncPowershell       
        npm i
        npm run build 
        ls -lh
    - name : copy to .net app
      run: |
        cp -r documentation/syncPowershell/build/* src/SyncPowershell/syncPowershellWebAPI/wwwroot/help/
        

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: docusaurusBuild
        path: 'documentation/syncPowershell/build/*'
        retention-days: 1

    - name: run test
      run: |
        cd  src
        cd SyncPowershell
        dotnet restore
        dotnet tool restore
        dotnet r test

    - name: dotnet publish
      run: |
          cd src
          cd SyncPowershell
          cd syncPowershellWebAPI
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app-dev
        path: ${{env.DOTNET_ROOT}}/myapp
        retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app-dev
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'syncpowershell'
          slot-name: 'Development'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E341142E0EE4479EAD9EEA1230445AAA }}
          package: .


    # - name: upload documentation to github pages
    #   if: ${{ github.ref == 'refs/heads/main' }}
    #   run: |
    #     cp -r documentation/syncPowershell/build/* docs/
        

    # - uses: EndBug/add-and-commit@v9
    #   if: ${{ github.ref == 'refs/heads/main' }}
    #   with:
    #     message: 'Deploy documentation'
    #     default_author: github_actions
    #     cwd: './docs'
